service: catfacts

provider:
  name: aws
  runtime: python2.7
  region: us-east-1
  stage: event

functions:
  catfacts:
    handler: main.handler
    events:
     - http:
         path: /
         method: post

