service: dadjoke

provider:
  name: aws
  runtime: python2.7
  region: us-east-1

functions:
  make_joke:
    handler: main.handler
    memorySize: 128
    timeout: 30
    events:
      - schedule:
          rate: "cron(22 10 ? * TUE *)"
          enabled: true
          name: "DadJokeEvent"
          description: "Runs the dad jokes"
