service: aws-python-alexa-skill-us-east

provider:
  name: aws
  runtime: python2.7
  region: us-east-1
  memorySize: 128

functions:
  fortune:
    handler: main.handler
    events:
      - alexaSkill

