service: slackmovie

provider:
  name: aws
  runtime: python2.7
  region: us-east-1
  stage: event
  environment:
    MOVIE_API_KEY: '123xyz'

functions:
  slackmovie:
    handler: main.handler
    events:
     - http:
         path: /
         method: post

